export const dataStub =
  [{
    _id: '597ed571bc4435bc7ebb60ee',
    name: 'Richard Jones',
    age: '55',
    sex: 'Male',
    race: 'White',
    month: 'December',
    day: '6',
    year: '2016',
    address: '3500 Ridgewood Dr',
    city: 'Hutchinson',
    state: 'KS',
    cause: 'Gunshot',
    dept: 'Hutchinson Police Department',
    armed: 'Firearm',
    __v: 0,
  },
  {
    _id: '597ed571bc4435bc7ebb6120',
    name: 'Zhonghua Li',
    age: '48',
    sex: 'Male',
    race: 'Asian/Pacific Islander',
    month: 'December',
    day: '24',
    year: '2016',
    address: '3400 Greenglade Ave',
    city: 'Pico Rivera',
    state: 'CA',
    cause: 'Gunshot',
    dept: "Los Angeles County Sheriff's Department",
    armed: 'Other',
    __v: 0,
  },
  {
    _id: '597ed571bc4435bc7ebb6107',
    name: 'Chassady LeClair',
    age: '44',
    sex: 'Male',
    race: 'Native American',
    month: 'December',
    day: '17',
    year: '2016',
    address: '3900 Grand Ave',
    city: 'Everett',
    state: 'WA',
    cause: 'Gunshot',
    dept: 'Lynnwood Police Department',
    armed: 'Unknown',
    __v: 0,
  },
  {
    _id: '597ed571bc4435bc7ebb6102',
    name: 'Earl Eubanks Jr',
    age: '32',
    sex: 'Male',
    race: 'Black',
    month: 'December',
    day: '13',
    year: '2016',
    address: 'Cherry St',
    city: 'Hampton',
    state: 'GA',
    cause: 'Gunshot',
    dept: 'Henry County Police Department',
    armed: 'Firearm',
    __v: 0,
  },
  {
    _id: '597ed571bc4435bc7ebb5fc7',
    name: 'Angel Torres Jr',
    age: '25',
    sex: 'Male',
    race: 'Hispanic/Latino',
    month: 'August',
    day: '27',
    year: '2016',
    address: 'W Thomas Rd and N 57th Ave',
    city: 'Phoenix',
    state: 'AZ',
    cause: 'Gunshot',
    dept: 'Phoenix Police Department',
    armed: 'Non-lethal firearm',
    __v: 0,
  }];
